remote_repository: https://github.com/zehonghuang/dev-repository.git
local_repository: "/Users/huangzehong/Documents/GitHub/dev-repository"
kube_config_map:
  context1: "context1"
  context2: "context2"
kube_config_file_map:
  context1: "context1"
  context2: "context2"
